version: "3"
services:
  customer-service:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./app:/app
  db:
    image: mysql:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/micro-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: false
    ports:
      - 3308:3306

